name: C++/CUDA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4


    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.16
      id: cuda-toolkit
      with:
        cuda: '12.0.0' 
        method: 'network'

    - name: Verify CUDA
      run: nvcc --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
